CREATE TABLE appointment_core (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    appointment_uuid VARCHAR(64) NOT NULL UNIQUE,
    patient_id BIGINT NOT NULL,
    provider_id BIGINT NOT NULL,
    id_cabinet BIGINT NOT NULL,
    facility_id BIGINT,
    appointment_type VARCHAR(50) NOT NULL,
    status VARCHAR(32) NOT NULL,
    reason VARCHAR(500),
    notes LONGTEXT,
    start_time DATETIME NOT NULL,
    end_time DATETIME,
    duration_minutes INT,
    location VARCHAR(255),
    primary_payer VARCHAR(255),
    insurance_plan VARCHAR(255),
    member_id VARCHAR(100),
    is_confirmed BOOLEAN DEFAULT FALSE,
    confirmed_at DATETIME,
    reminder_sent_at DATETIME,
    cancelled_at DATETIME,
    cancellation_reason VARCHAR(255),
    virtual_meeting_link VARCHAR(500),
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME,
    version BIGINT DEFAULT 0,
    
    INDEX idx_appointment_uuid (appointment_uuid),
    INDEX idx_appointment_patient (patient_id),
    INDEX idx_appointment_provider (provider_id),
    INDEX idx_appointment_cabinet (id_cabinet),
    INDEX idx_appointment_start_time (start_time),
    INDEX idx_appointment_status (status),
    INDEX idx_appointment_updated_at (updated_at)
);
